; Daytona USA 2 Power Edition views.

[ Bezel ]
Artwork = "Assets/Bezel.png"
X = 0.100000
Y = 0.000000
Width = 0.800000
Height = 1.000000
WideScreen = 0
CRTCurvature = 1

[ Bezel 2 ]
Artwork = "Assets/Bezel2.png"
X = 0.166667
Y = 0.055556
Width = 0.666667
Height = 0.888889
WideScreen = 0
CRTCurvature = 1

[ Widescreen ]
X = 0.0
Y = 0.0
Width = 1.0
Height = 1.0
WideScreen = 1
CRTCurvature = 0
