##
## Supermodel
## A Sega Model 3 Arcade Emulator.
## Copyright 2003-2025 The Supermodel Team
##
## This file is part of Supermodel.
##
## Supermodel is free software: you can redistribute it and/or modify it under
## the terms of the GNU General Public License as published by the Free
## Software Foundation, either version 3 of the License, or (at your option)
## any later version.
##
## Supermodel is distributed in the hope that it will be useful, but WITHOUT
## ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
## FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
## more details.
##
## You should have received a copy of the GNU General Public License along
## with Supermodel.  If not, see <http://www.gnu.org/licenses/>.
##

#
# Makefile.UNIX
#
# Makefile for UNIX/Linux systems.
#


###############################################################################
# Build Options
###############################################################################

DELETE = rm -d -r -f


###############################################################################
# Release Package Options
###############################################################################

PKG_TYPE = tgz


###############################################################################
# Platform Configuration
#
# Edit library and include paths as needed.
###############################################################################

#
# Must be included first
#
include Makefiles/Options.inc

#
# Optional OpenGL ES 3.2 build. This is intentionally supported only by the
# UNIX/Linux makefile; macOS uses desktop OpenGL.
#
GLES =
ifneq ($(filter $(strip $(GLES)),0 1),$(strip $(GLES)))
	override GLES =
endif
SUPERMODEL_GLES_BUILD =

#
# Optional SDL Wayland-preferred build. SDL still owns the platform backend;
# no direct Wayland libraries are required by Supermodel.
#
WAYLAND =
ifneq ($(words $(strip $(WAYLAND))),1)
	override WAYLAND =
else ifneq ($(filter $(strip $(WAYLAND)),0 1),$(strip $(WAYLAND)))
	override WAYLAND =
endif

#
# Toolchain
#
CC = gcc
CXX = g++
LD = gcc

#
# SDL
#

SDL2_CFLAGS = `sdl2-config --cflags`
SDL2_LIBS = `sdl2-config --libs`
SDL2_LIBS += -lSDL2_net

#
#	UNIX-specific
#

PLATFORM_CXXFLAGS = $(SDL2_CFLAGS) -O3
ifeq ($(strip $(WAYLAND)),1)
	PLATFORM_CXXFLAGS += -DSUPERMODEL_PREFER_WAYLAND
endif
ifeq ($(strip $(GLES)),1)
	SUPERMODEL_GLES_BUILD = 1
	PLATFORM_CXXFLAGS += -DSUPERMODEL_GLES -DIMGUI_IMPL_OPENGL_ES3
	PLATFORM_LDFLAGS = $(SDL2_LIBS) -lGLESv2 -lz -lm -lstdc++ -lpthread
else
	PLATFORM_LDFLAGS = $(SDL2_LIBS) -lGL -lGLU -lz -lm -lstdc++ -lpthread
endif
PLATFORM_BINARY_EXTENSION =
PLATFORM_TRACK_BUILD_CONFIG = 1


###############################################################################
# Core Makefile
###############################################################################

PLATFORM_SRC_FILES = \
	Src/OSD/Unix/FileSystemPath.cpp

include Makefiles/Rules.inc

clean:
	$(SILENT)echo Cleaning up \"$(BIN_DIR)\" and \"$(OBJ_DIR)\"...
	$(SILENT)$(DELETE) $(BIN_DIR)
	$(SILENT)$(DELETE) $(OBJ_DIR)
