name: make-macos
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: install_dependencies
      run: |
        brew update
        brew install sdl2
        brew install sdl2_net
    - name: make
      run: make -f Makefiles/Makefile.OSX
    - uses: actions/upload-artifact@v4
      with:
        name: supermodel
        path: bin/supermodel
