name: make-macos
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    # - name: install_dependencies
    #   run: |
    #     brew update
    #     brew install sdl2
    #     brew install sdl2_net
    - name: Setup SDL2 frameworks
      uses: BrettDong/setup-sdl2-frameworks@main
      with:
        sdl2: latest
        sdl2-net: latest
        # sdl2-image: 2.6.3
        # sdl2-mixer: none
        # sdl2-net: 2.2.0
    - name: make
      run: make -f Makefiles/Makefile.OSX
    - uses: actions/upload-artifact@v4
      with:
        name: supermodel
        path: bin/supermodel
