name: make-linux
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install_dependencies
      run: |
        sudo apt install libsdl2-dev
        sudo apt install libsdl2-net-dev
    - name: make
      run: make -f Makefiles/Makefile.UNIX
